### ISSUE TITLE
Assessment results

### ISSUE THREAD

**Issue by francepack** [stacyp2006/mod_0_skills#1]
@stacyp2006 
You've done well enough here to merit passing with a few revisions. Well done! Please make any updates by Monday, here's what we're looking for:

- [ ] For your boolean attribute names, try to add a word to the front to give them a sense of the question they help to answer. `isDelicious` from the variables files is a good example of this.

- [ ] `spaceAvailable` doesn't read quite like your other methods. Add an active word to the start of your name here.

Let me know if you have questions!

**Comment by stacyp2006** [comment]
Hi Mason! I've completed the revisions and pushed to git. Let me know if you need anything else. Thanks!
